services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    secrets:
      - db-password
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres
    container_name: pg
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password

    secrets:
      - db-password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 10s
      retries: 5

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      pg:
        condition: service_healthy

  proxy:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:81
    depends_on:
      backend:
        condition: service_started

volumes:
  tes-pg:

secrets:
  db-password:
    file: db/password.txt
